name: Android CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v1
        with:
          sdk-platform: 'platforms;android-30'
          build-tools: '30.0.3'
          ndk-version: '21.4.7075529'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --no-daemon

      - name: Sign app APK
        run: |
          export JAVA_HOME="${{ env.JDK_DIR }}"
          export PATH="${{ env.JDK_DIR }}/bin:${{ env.PATH }}"

          jarsigner \
            -sigalg SHA256withRSA \
            -digestalg SHA-256 \
            -keystore ${{ secrets.ANDROID_KEYSTORE_FILE }} \
            -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.ANDROID_KEY_PASSWORD }} \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            ${{ secrets.ANDROID_KEY_ALIAS }}

          zipalign -v 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/app-release-signed.apk

      - name: Upload to Release Action
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: xqe-sesame-${{ github.event.release.tag_name }}.apk
          path: app/build/outputs/apk/release/app-release-signed.apk
          repo-token: ${{ github.token }}
          content-type: application/zip
