name: Android CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v1
        with:
          sdk-platform: 'platforms;android-30'
          build-tools: '30.0.3'
          ndk-version: '21.4.7075529'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --no-daemon

      - name: Sign app APK
        uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 30.0.3

      - name: Upload to Release Action
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: xqe-sesame-${{ github.event.release.tag_name }}.apk
          path: ${{ steps.sign_app.outputs.signedFile }}
          repo-token: ${{ github.token }}
          content-type: application/zip
